### ISSUE TITLE
[bash] Error redirection `2>`

### ISSUE THREAD

**Issue by thomasdenecker** [sandbox-bio/sandbox.bio#21]
Hello Robert, 

In one of our scenarios, we want to look at bash redirects. We've noticed that some errors aren't handled as `stderr` but more as bug display on the WASM side.

For example, if you open the "Command lines" playground and run the following command: 

```bash
guest@sandbox$ grep foo tutorials/
(null): tutorials/: Is a directory
```

If we try to redirect as follows : 

```bash
guest@sandbox$ grep foo tutorials/ 2> error.log
(null): tutorials/: Is a directory
```

The `error.log` file exists but is empty. 

Do you have an idea? We've explored the code a little, and we found in `src/terminal/cli.js` file the part to manage redirection. We have the impression that the problem is the : `(null):`. 

On the other hand, if we write

```bash
guest@sandbox$ man 2> error.log
guest@sandbox$ cat error.log 
No manual entry for undefined
```
So, the redirect has the expected behavior. 

Thanks in advance for your feedback

**Comment by robertaboukhalil** [comment]
Hey @thomasdenecker,

https://github.com/sandbox-bio/sandbox.bio/blob/696ba4b9724c021ec585714d025e0c87b4a35b25/app/src/terminal/cli.js#L266-L267

From the code above, looks like I only added support for `2>&1` but not `2>somefile`. I wonder whether it works with `man` but not other commands because `man` is simulated with JS code whereas the others are WebAssembly modules being run.

In the new engine I'm working on, this won't be an issue because I won't need to reimplement bash internals! To get this working in the current version, we would need to parse for `redirect.type` = `redirectFd` (I use https://github.com/grncdr/js-shell-parse to parse shell commands and they mark `2>somefile` patterns as `redirectFd`).

If you don't need this soon, it's probably easier to wait for the new engine 🙂
