### ISSUE TITLE
New scenario with GameShell in sandbox

### ISSUE THREAD

**Issue by pierrepo** [sandbox-bio/sandbox.bio#88]
Could it be possible to create a new training scenario with GameShell (https://github.com/phyver/GameShell), that is a game to teach the Unix shell?

**Comment by robertaboukhalil** [comment]
Very interesting! I tried it and it runs but the beginning is a bit slow to load.

I would need to look into why it's so slow to load the animation at the beginning, and it doesn't work with root so I might need to have the user be non-root (not a bad idea in general).

---

If you want to test it in the meantime:
* Download https://github.com/phyver/GameShell/releases/download/latest/gameshell.sh to your local computer
* Go to https://sandbox.bio/tutorials/playground
* Click the three dots in the top right of the terminal -> Mount local files -> Select gameshell.sh
* It doesn't work with user `root` so:

```bash
adduser guest
su guest
cp /root/tutorial/gameshell.sh ~
cd ~
bash gameshell.sh
```

**Comment by pierrepo** [comment]
Thanks @robertaboukhalil for taking this request into account.

The game is indeed super slow to load and run. Maybe this is because the shell script `gameshell.sh` contains itself the archive of the game (starting line 235).

**Comment by pierrepo** [comment]
From my computer, I downloaded `gameshell.sh` and extracted the game:

```
curl https://github.com/phyver/GameShell/releases/download/latest/gameshell.sh --output gameshell.sh
bash gameshell.sh -X
```
This produced the archive `gameshell.tgz` that I uploaded into Sandbox playground.

In user mode, I ran
```
tar zxvf gameshell.tgz
cd gameshell
bash start.sh
```

Better than before, but still slow.

**Comment by robertaboukhalil** [comment]
Thanks Pierre! Looking into it more, I found a few more things:

* We could extract the tar ahead of time and run `./start.sh -C` to resume instead of start over
* Part of `start.sh` runs a bunch of tests that we could comment out
* Drawing the boxes in `box.sh` is surprisingly slow, a few seconds!
* Every time the prompt is shown, it executes `gsh pcm` which returns the mission number, but it takes a couple seconds to run which I'm not sure why

There are probably more so unfortunately it would take too many changes to gameshell to run smoothly in the browser.

Alternatively, it might work better to convert the missions into standard sandbox.bio tutorials with exercises, where the above would no longer be issues 🤔

**Comment by pierrepo** [comment]
So maybe it's not a good idea to put gameshell into sandbox for now. Should we close this issue?
